// <auto-generated />
using System;
using CarRental.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRental.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250810113528_SeedCarsTable")]
    partial class SeedCarsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRental.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94d64bbe-ca9f-4de2-91c6-fc065a646c8f"),
                            Brand = "Toyota",
                            Colour = "Red",
                            Description = "A comfortable sedan for family trips.",
                            Image = "/images/toyota_camry.jpg",
                            Model = "Camry",
                            PricePerDay = 3000m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("1e8f3a5b-7c4d-4e9a-8b1f-9c0a6d5e7f2a"),
                            Brand = "Ford",
                            Colour = "Orange",
                            Description = "A compact SUV for city and long drives.",
                            Image = "/images/ford_ecosport.jpg",
                            Model = "Ecosport",
                            PricePerDay = 2500m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("f2c9e8d7-6b5a-4e3d-9a8c-1f0b2e3d4c5b"),
                            Brand = "Hyundai",
                            Colour = "Red",
                            Description = "A stylish hatchback perfect for the city.",
                            Image = "/images/hyundai_i20.jpg",
                            Model = "i20",
                            PricePerDay = 2000m,
                            Status = "Booked"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
